services:
  - type: web
    name: sales-management
    runtime: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
    preDeployCommand: |
      python manage.py migrate --noinput
      python manage.py clear_db_cache
    startCommand: gunicorn sales_management_project.wsgi:application
