services:
  - type: web
    name: sales-management
    runtime: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
    preDeployCommand: python manage.py migrate
    startCommand: gunicorn sales_management_project.wsgi:application
